---
title: BCGG Water Refilling Station
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sliderItem:
    title: Slider Item
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: |
  BCGG WATER REFILLING STATION
location: Burgundy Corporate Tower, 252 Sen. Gil Puyat, <br/> Makati City, Philippines
contact:
- name: Globe
  number: "+639166149709"
- name: Smart
  number: "+639476971265"
- name: Landline
  number: 7369026
baseurl: 
url: http://yourdomain.com
markdown: kramdown
sass:
  style: compressed
