# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BCGG Water Refilling Station
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  BCGG WATER REFILLING STATION
location: Burgundy Corporate Tower, 252 Sen. Gil Puyat, <br/> Makati City, Philippines

contact:
  - name: Globe
    number: "+639166149709"

  - name: Smart
    number: "+639476971265"

  - name: Landline
    number: "7369026"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: compressed

#Collections
collections:
    sliderItem:
      output: true